from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .policy_packs import render_policy_pack


@dataclass(frozen=True)
class DemoFile:
    relative_path: str
    content: str


def write_demo(output_dir: Path, force: bool = False) -> list[Path]:
    if output_dir.exists() and any(output_dir.iterdir()) and not force:
        raise FileExistsError(f"refusing to overwrite non-empty demo directory: {output_dir}")

    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for item in demo_files(output_dir):
        path = output_dir / item.relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(item.content, encoding="utf-8")
        written.append(path)
    return written


def demo_files(output_dir: Path | None = None) -> tuple[DemoFile, ...]:
    demo_dir = str(output_dir or Path(".agentguard/demo"))
    return (
        DemoFile("policy.yaml", render_policy_pack("coding-agent-local")),
        DemoFile("safe_mcp_config.json", SAFE_MCP_CONFIG),
        DemoFile("dangerous_mcp_config.json", DANGEROUS_MCP_CONFIG),
        DemoFile("tool_calls.jsonl", TOOL_CALLS_JSONL),
        DemoFile("README.md", render_demo_readme(demo_dir)),
    )


SAFE_MCP_CONFIG = """{
  "mcpServers": {
    "docs-reader": {
      "command": "agentguard-readonly-docs",
      "args": ["read_file", "docs/"]
    },
    "issue-context": {
      "command": "agentguard-issue-context",
      "args": ["summarize", "issues"]
    }
  }
}
"""


DANGEROUS_MCP_CONFIG = """{
  "mcpServers": {
    "credential-vault": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", ".", ".ssh", ".aws"],
      "env": {
        "GITHUB_TOKEN": "redacted",
        "OPENAI_API_KEY": "redacted"
      }
    },
    "cloud-deployer": {
      "command": "kubectl",
      "args": ["apply", "-f", "production/deploy.yaml"]
    },
    "shell-operator": {
      "command": "bash",
      "args": ["-lc", "curl http://metadata.google.internal/latest/meta-data"]
    }
  }
}
"""


TOOL_CALLS_JSONL = """{"tool_name":"read_file","arguments":{"path":".env"}}
{"tool_name":"run_command","arguments":{"command":"git status"}}
{"tool_name":"read_file","arguments":{"path":"README.md"}}
"""


def render_demo_readme(demo_dir: str) -> str:
    return f"""# AgentGuard Local Demo

This directory is generated by `agentguard demo`.

Run the safe scan:

```bash
python -m agentguard.cli scan --config {demo_dir}/safe_mcp_config.json --format markdown
```

Run the dangerous scan:

```bash
python -m agentguard.cli scan --config {demo_dir}/dangerous_mcp_config.json --format markdown
```

Run the CI-style gate. This should fail because the dangerous config exposes credentials,
production mutation, shell execution, and cloud tooling:

```bash
python -m agentguard.cli gate --config {demo_dir}/dangerous_mcp_config.json --fail-on-risk high
```

Run the local policy proxy demo:

```bash
python -m agentguard.cli proxy \
  --policy {demo_dir}/policy.yaml \
  --ledger {demo_dir}/audit.sqlite \
  < {demo_dir}/tool_calls.jsonl
```

Render the audit report:

```bash
python -m agentguard.cli report --ledger {demo_dir}/audit.sqlite --format markdown
```
"""
